### ISSUE TITLE
Unable to locate AzSpeech under `Project Settings > Plugins` for Unreal Engine (v 5.1.1)

### ISSUE THREAD

**Issue by iDataist** [lucoiso/UEAzSpeech#228]
I have successfully installed the AzSpeech plugin (v 1.3.12) within Unreal Engine. However, I am unable to locate AzSpeech under `Project Settings > Plugins`.

<img width="1248" alt="Screenshot 2023-08-28 at 3 06 48 PM" src="https://github.com/lucoiso/UEAzSpeech/assets/46846986/54c36016-67e6-4929-99cc-486e861a43f8">

<img width="1501" alt="Screenshot 2023-08-28 at 3 10 40 PM" src="https://github.com/lucoiso/UEAzSpeech/assets/46846986/e9a9d963-48e8-4e46-9da9-229bc835c0be">

**Comment by lucoiso** [comment]
Hello @iDataist ! 

Unfortunately, the MacOS version in the marketplace is outdated (and I can't remove heheh) and experimental because I currently don't have a MacOS platform to test here. :/

I recently made a lot of fixes and updates and recommend trying a newer version:

You can find the recent releases here: https://github.com/lucoiso/UEAzSpeech/releases

To use in MacOS you'll need to:
1. Download the plugin .zip and extract to: YOUR_PROJECT_DIRECTORY/Plugins
2. Compile your project with C++17 (Enable it in XCode)

---

Any issue, feel free to reply! :)

**Comment by iDataist** [comment]
Hello @lucoiso, I appreciate your quick reply. I'm uncertain about the procedure for enabling C++17 and compiling the Unreal Engine project through XCode. Could you kindly offer more comprehensive instructions or additional clarification regarding this particular step? Your assistance in this matter would be highly valued.

**Comment by lucoiso** [comment]
Sorry for the long delay, I didn't receive the notification. :S

I'll look for more information about this error and MacOS environment (or maybe create a separated branch without some C++17 features to avoid similar issues)
